server:
  host: localhost
  port: 8081
  servlet:
    context-path: "/file"
# ==========applicationName + druid-mysql8 driver===================
spring:
  application:
    name: csplatform-file-service
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      enabled: true
      file-size-threshold: 5MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3307/csplatform_file?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: wx
    # 关键修正：使用MySQL官方驱动类
    driver-class-name: com.mysql.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: wangxing
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml  # XML映射文件位置
  type-aliases-package: com.example.entity      # 实体类所在包，用于别名简化
  configuration:
    map-underscore-to-camel-case: true          # 自动开启下划线到驼峰命名的映射
minio:
  bucketName: singing
  endpoint: http://${server.host}:9000
  accessKey: oxSs7bSxVwrqBIo8N4VN
  secretKey: uISC7CG0amOn6vn7WSYFTWMWpymS5xP7mJch1Oxp
  expire: 7200
feign:
  client:
    config:
      service:
        userService: "http://localhost:8083"
        chatService: "http://localhost:8085"
        fileService: "http://localhost:8081"
        courseService: "http://locahost:8084"
      path:
        userPath: "/user"
        chatPath: "/chat"
        filePath: "/file"
        coursePath: "/course"