server:
  port: 8082
  servlet:
    context-path: "/chat"
# ==========applicationName + druid-mysql8 driver===================
spring:
  application:
    name: csplatform-file-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3307/csplatform_chat?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: wx
    # 关键修正：使用MySQL官方驱动类
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml  # XML映射文件位置
  type-aliases-package: com.example.entity      # 实体类所在包，用于别名简化
  configuration:
    map-underscore-to-camel-case: true          # 自动开启下划线到驼峰命名的映射
feign:
  client:
    config:
      service:
        userService: "http://localhost:8083"
        chatService: "http://localhost:8082"
        fileService: "http://localhost:8081"
      path:
        userPath: "/user"
        chatPath: "/chat"
        filePath: "/file"