spring:
  cloud:
    gateway:
      routes:
        - id: csplatform-file-router  # 路由ID，唯一即可
          uri: http://localhost:8081  # 目标服务静态URI
          predicates:
            - Path=/api/file/**  # 断言条件：匹配路径
          filters:
            - StripPrefix=1  # 过滤器：去掉路径中的第一段（例如/api）
        - id: csplatform-chat-router
          uri: http://localhost:8085
          predicates:
            - Path=/api/chat/**
          filters:
            - StripPrefix=1
        - id: csplatform-user-router
          uri: http://localhost:8083
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: csplatform-course-router
          uri: http://localhost:8084
          predicates:
            - Path=/api/course/**
          filters:
            - StripPrefix=1
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "http://localhost:5173"  # 部署时注意这里TODO：指定具体前端地址
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            max-age: 3600
      default-filters:  # 添加全局过滤器
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Methods, RETAIN_FIRST
server:
  port: 8080